### ISSUE TITLE
The library is not working with Python 3.10 (removed loop as a parameter to most asyncio functions)

### ISSUE THREAD

**Issue by tamaroth** [gawel/aiocron#22]
[Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#whatsnew310-removed) has removed the `loop` parameter from most of its functions (it was deprecated since Python 3.8). As a result it is currently impossible to use the library with the newest Python version.

**Comment by gawel** [comment]
Can you add a traceback or something ? Doesn't looks like aiocron is using the high level api

**Comment by tamaroth** [comment]
Sure, should have added it right away:

```python
2021-11-19 12:16:44.002374 [error    ] Exception in callback None()
handle: <TimerHandle cancelled when=140694.05696083547> [asyncio] 
Traceback (most recent call last):
  File "/home/tamaroth/.pyenv/versions/3.10.0/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Work/repos/cim/virtualenv/lib/python3.10/site-packages/aiocron/__init__.py", line 80, in call_next
    self.call_func()
  File "/Work/repos/cim/virtualenv/lib/python3.10/site-packages/aiocron/__init__.py", line 84, in call_func
    asyncio.gather(
TypeError: gather() got an unexpected keyword argument 'loop'
```

This is described also [here](https://docs.python.org/3/library/asyncio-task.html#running-tasks-concurrently):

```
Deprecated since version 3.8, removed in version 3.10: The loop parameter. This function has been implicitly getting the current running loop since 3.7. See What’s New in 3.10’s Removed section for more information.
```

I have manually commented out the `loop` parameter [here](https://github.com/gawel/aiocron/blob/17de9d15fc3ed51ad0d2da64b11577dfe64db6c7/aiocron/__init__.py#L90) so it works for me locally currently. Obviously this is not a solution for the library itself. It'd be easier if you were to support only Python 3.7+, but otherwise I suppose you will have to do some version detection magic.

**Comment by gawel** [comment]
Or avoid using gather which seems to be the only problem. Got it. Thanks
